name 'mysnmp'
source_url       'https://github.com/emo3/mysnmp'
issues_url       'https://github.com/emo3/mysnmp/issues'
maintainer 'The Authors1'
maintainer_email 'you1@example.com'
chef_version '>= 16.0'
license 'All Rights Reserved'
description 'Installs/Configures mysnmp'
version '0.2.0'

supports 'redhat'
supports 'centos'
supports 'almalinux'

depends 'snmp'
